spring:
      data:
          mongodb:
                authentication: none
                database: otus21
                port: 27017
                host: localhost

management:
    endpoints:
          web:
            exposure:
                  include: "*"